### ISSUE TITLE
setFetchMode()

### ISSUE THREAD

**Issue by tibormarias** [thedigicraft/Atom.CMS3#1]
Fatal error: Call to undefined method mysqli_result::setFetchMode() in /var/www/site/data/www/mysite/functions/data.php on line 6

Why should it happen? Can you give the whole database structure?

Thanks in advance!

**Comment by thedigicraft** [comment]
@tibormarias I just pushed the sql file.  I will look at that error.  I am wondering if your PHP version is new enough.

**Comment by thedigicraft** [comment]
I figured it out.  I had originally set the connection.php file to be ignored by Git.   Download that and update it to your credentials.
